from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class ToolCallSchema(BaseModel):
    tool_name: str
    tool_input: Dict[str, Any]

class AgentResponse(BaseModel):
    final_answer: str = Field(..., description="The final answer from the agent")
    plan: Optional[str] = Field(None, description="The plan generated by the agent")
    tool_calls: List[ToolCallSchema] = Field(default_factory=list, description="List of tools used")
    reasoning_summary: str = Field(..., description="A safe summary of intermediate reasoning")
